// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpqqmTTav_t1FSVi67ViHxSlO8gOWLVpI',
    appId: '1:35061672562:web:eda5021faf4c8ce9efb0eb',
    messagingSenderId: '35061672562',
    projectId: 'mynotebook-flutter',
    authDomain: 'mynotebook-flutter.firebaseapp.com',
    storageBucket: 'mynotebook-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUE4806vKYR7n6_syiyx5zznbNhGtpl-k',
    appId: '1:35061672562:android:145337edd6a9ec0cefb0eb',
    messagingSenderId: '35061672562',
    projectId: 'mynotebook-flutter',
    storageBucket: 'mynotebook-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtRXjTntBnna-cxjiGgMW92P2EMrIPR_0',
    appId: '1:35061672562:ios:fdde3cd41d32fbb0efb0eb',
    messagingSenderId: '35061672562',
    projectId: 'mynotebook-flutter',
    storageBucket: 'mynotebook-flutter.appspot.com',
    iosBundleId: 'com.example.mynotebook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtRXjTntBnna-cxjiGgMW92P2EMrIPR_0',
    appId: '1:35061672562:ios:312fcfc55e8d5048efb0eb',
    messagingSenderId: '35061672562',
    projectId: 'mynotebook-flutter',
    storageBucket: 'mynotebook-flutter.appspot.com',
    iosBundleId: 'com.example.mynotebook.RunnerTests',
  );
}
